// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// derif
Rcpp::List derif(arma::mat c, arma::mat w, arma::mat d, arma::mat core, arma::uvec idx);
RcppExport SEXP _scBatch_derif(SEXP cSEXP, SEXP wSEXP, SEXP dSEXP, SEXP coreSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type c(cSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type core(coreSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(derif(c, w, d, core, idx));
    return rcpp_result_gen;
END_RCPP
}
// scBatchCpp
arma::mat scBatchCpp(arma::mat c, arma::mat w, arma::mat d, int m, double max, double step, double tol, Rcpp::Function derif, bool verbose);
RcppExport SEXP _scBatch_scBatchCpp(SEXP cSEXP, SEXP wSEXP, SEXP dSEXP, SEXP mSEXP, SEXP maxSEXP, SEXP stepSEXP, SEXP tolSEXP, SEXP derifSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type c(cSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w(wSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type max(maxSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< Rcpp::Function >::type derif(derifSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(scBatchCpp(c, w, d, m, max, step, tol, derif, verbose));
    return rcpp_result_gen;
END_RCPP
}
